#ifndef MAL_PCC_CONFIG_C_
#define MAL_PCC_CONFIG_C_

#include "MAL/PCC_Config.h"

/*void enable_PCC_PORTA(void){
	PCC->PCCn[PCC_PORTA_INDEX]=0x40000000u;
}*/

void PCC_PORTB(void){
	PCC->PCCn[PCC_PORTB_INDEX]=0x40000000u;
}

void PCC_PORTC(void){
	PCC->PCCn[PCC_PORTC_INDEX]=0x40000000u;
}

void PCC_PORTD(void){
	PCC->PCCn[PCC_PORTD_INDEX]=0x40000000u;
}

void PCC_PORTE(void){
	PCC->PCCn[PCC_PORTE_INDEX]=0x40000000u;
}

void PCC_LPIT(void){
	PCC->PCCn[PCC_LPIT_INDEX]=PCC_PCCn_PCS(6);
	PCC->PCCn[PCC_LPIT_INDEX]=0x40000000u;
}

#endif /* MAL_PCC_CONFIG_C_ */
