#include "MAL/PORT_Config.h"

/*void set_PORTA(T_ULONG PIN,T_ULONG DIR){
	PORTA->PCR[PIN]=DIR;
}*/

void SET_PORTB(T_ULONG PIN,T_ULONG DIR){
	PORTB->PCR[PIN]=DIR;
}

void SET_PORTC(T_ULONG PIN,T_ULONG DIR){
	PORTC->PCR[PIN]=DIR;
}

void SET_PORTD(T_ULONG PIN,T_ULONG DIR){
	PORTD->PCR[PIN]=DIR;
}

void SET_PORTE(T_ULONG PIN,T_ULONG DIR){
	PORTE->PCR[PIN]=DIR;
}
