#include "HAL/TIMERS.h"

void ms_TIMER(T_ULONG t_uTime){
	PCC->PCCn[PCC_LPIT_INDEX] = PCC_PCCn_PCS(6);
	PCC->PCCn[PCC_LPIT_INDEX] |= PCC_PCCn_CGC_MASK;
	LPIT0->MCR = 0x00000001;
	LPIT0->TMR[0].TVAL = 40000*t_uTime;
	LPIT0->TMR[0].TCTRL = 0x00000001;
}

void TIMER_ENABLE(void){
	while(0 == (LPIT0->MSR & LPIT_MSR_TIF0_MASK)){}
	LPIT0->MSR |= LPIT_MSR_TIF0_MASK;
}
