#ifndef MAL_GPIO_CONFIG_H_
#define MAL_GPIO_CONFIG_H_

#include "S32K144.h"
#include "MAL/Definitions.h"

//void PORTA_SET_INPUT(T_ULONG PIN);
void PORTB_AS_INPUT(T_ULONG PIN);
void PORTC_AS_INPUT(T_ULONG PIN);
void PORTD_AS_INPUT(T_ULONG PIN);
void PORTE_AS_INPUT(T_ULONG PIN);

//void PORTA_SET_OUTPUT(T_ULONG PIN);
void PORTB_AS_OUTPUT(T_ULONG PIN);
void PORTC_AS_OUTPUT(T_ULONG PIN);
void PORTD_AS_OUTPUT(T_ULONG PIN);
void PORTE_AS_OUTPUT(T_ULONG PIN);

//void PORTA_OUTPUT_HIGH(T_ULONG PIN);
void PORTB_HIGH(T_ULONG PIN);
void PORTC_HIGH(T_ULONG PIN);
void PORTD_HIGH(T_ULONG PIN);
void PORTE_HIGH(T_ULONG PIN);

//void PORTA_OUTPUT_LOW(T_ULONG PIN);
void PORTB_LOW(T_ULONG PIN);
void PORTC_LOW(T_ULONG PIN);
void PORTD_LOW(T_ULONG PIN);
void PORTE_LOW(T_ULONG PIN);

#endif /* MAL_LIB_GPIO_H_ */
